<?php 


define('BASE_NAME', 'CODEM');
define('BASE_TITLE', 'COOPERATIVE POUR LE DEVELLOPPEMENT MITUEL');
define('BASE_NIF', '4002010405');
define('BASE_RC', 'SC 0148/2022');
define('BASE_ADDRESS', 'KINAMA');